sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - main
before_install:
  - npm install hexo -g
  - git clone https://github.com/xiaowenxia/git-inside.git -b xiaowenxia.github.io/git-inside
  - cd git-inside
script:
  - 
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: xiaowenxia.github.io/git-inside
  local-dir: git-inside/public
  verbose: true
